apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
  labels:
    name: portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: iuriikogan/portfolio:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 65534
          runAsGroup: 65534
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - all
            add:
              - NET_ADMIN
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1280Mi"
            cpu: "1000m"
        volumeMounts: 
        - name: cache
          mountPath: /var/cache/nginx
        - name: run  
          mountPath: /var/run
        ports:
        - containerPort: 80
        livenessProbe: 
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes: 
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: portfolio
spec:
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio 
spec:
  ingressClassName: nginx
  rules:
  - host: portfolio.localhost
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: portfolio-service
              port:
                number: 80
